CREATE TABLE orders (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    client_id INT UNSIGNED NOT NULL,
    student_id INT UNSIGNED NOT NULL,
    service_id INT UNSIGNED NOT NULL,
    status ENUM('pending', 'in_progress', 'delivered', 'revision_requested', 'completed', 'cancelled') NOT NULL,
    requirements TEXT NOT NULL,
    requirement_files JSON,
    delivery_message TEXT NULL,
    delivery_files JSON NULL,
    price DECIMAL(10,2) NOT NULL,
    commission_rate DECIMAL(5,2) NOT NULL,
    deadline TIMESTAMP NOT NULL,
    revision_count INT UNSIGNED DEFAULT 0,
    max_revisions INT UNSIGNED DEFAULT 3,
    completed_at TIMESTAMP NULL,
    cancelled_at TIMESTAMP NULL,
    cancellation_reason TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (client_id) REFERENCES users(id),
    FOREIGN KEY (student_id) REFERENCES users(id),
    FOREIGN KEY (service_id) REFERENCES services(id),
    INDEX idx_client_status (client_id, status),
    INDEX idx_student_status (student_id, status),
    INDEX idx_status_deadline (status, deadline),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
